### ISSUE TITLE
run nqptp as non root

### ISSUE THREAD

**Issue by th0u** [mikebrady/nqptp#12]
Hi,
thank you for your excellent work.

Today I installed shairport-sync with AirPlay2 support.
According the documentation, nqptp (must) run as root.
Why is this? 
I assume this is due to listening to ports < 1024.

After creation of a user / group "nqptp" and patching nqptp.service (replace root by nqptp) and running this command
`setcap 'cap_net_bind_service=+ep' /usr/local/bin/nqptp`

nqptp runs as user nqptp and I was able to stream from my MBP2020 macOS12 to shairport-sync.

`udp        0      0 0.0.0.0:9000            0.0.0.0:*                           2702/nqptp           off (0.00/0/0)
udp        0      0 0.0.0.0:319             0.0.0.0:*                           2702/nqptp           off (0.00/0/0)
udp        0      0 0.0.0.0:320             0.0.0.0:*                           2702/nqptp           off (0.00/0/0)
udp6       0      0 :::9000                 :::*                                2702/nqptp           off (0.00/0/0)
udp6       0      0 :::319                  :::*                                2702/nqptp           off (0.00/0/0)
udp6       0      0 :::320                  :::*                                2702/nqptp           off (0.00/0/0)`

`nqptp     2702  1.8  0.0   2212   460 ?        SLs  19:20   0:13 /usr/local/bin/nqptp`

I am not sure how I can verify that nqptp is definitely working, but I observed that when nqptp is stopped that I can not stream from iPhone nor from macOS. If I then start nqpto then its possible to stream from macOS12. So I assume nqptp is working while not running as root.

Any other hints to verify functionality running nqptp as non root?

TIA, T

edit: streaming from iOS is also not possible when nqptp was stopped. This seems to be expected.

**Comment by mikebrady** [comment]
Thanks. Yes, the only motivation was for access to ports below 1024. If you can run `nqptp` with the argument `-v`, it’ll log some information so you can see that it’s working.

**Comment by th0u** [comment]
Thnx for your feedback. I can confirm that nqptp is working.
Btw I tested this on raspbian bullseye.

**Comment by mikebrady** [comment]
I'll close this, if that's okay?

**Comment by th0u** [comment]
yes sure. Thank you for your excellent work!
