### ISSUE TITLE
Security contact / reporting process

### ISSUE THREAD

**Issue by wfrisch** [mikebrady/nqptp#23]
There doesn't seem to be an established process for reporting (potential) security vulnerabilities in nqptp.

This could be solved either via a security contact listed in `SECURITY.md`,
or by enabling [private security reporting on GitHub](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).

**Comment by mikebrady** [comment]
Thanks for the suggestion!

**Comment by wfrisch** [comment]
I would like to share a few comments about nqptp's security, but I can't find a valid contact address.
Could you please, so I can reply? 
Email: wolfgang.frisch@suse.com
Thanks!

**Comment by mikebrady** [comment]
Hi Wolfgang. I [think I have] enabled private security reporting for NQPTP. If you'd be kind enough to try it, or to revert here, that would be great, thanks.

**Comment by jsegitz** [comment]
Hi Mike, sorry didn't see your reply here. Wolfgang is on parental leave, I'll sent you his email as private report. Thanks for enabling that

**Comment by mikebrady** [comment]
Working on this...

**Comment by mikebrady** [comment]
I think this has been done -- feel free to open another issue if not.
