### ISSUE TITLE
-bash: ./configure: No such file or directory

### ISSUE THREAD

**Issue by Joeknx** [mikebrady/nqptp#24]
Hi,

I'm on a Raspberry and I try to update. When I type "./configure --with-systemd-startup" I get the message "-bash: ./configure: No such file or directory"

Did I do something wrong?

Thanks!

**Comment by mikebrady** [comment]
Thanks. Did you do the preceding `$ autoreconf -fi`? What did it say?

**Comment by mikebrady** [comment]
Aha -- there's a missing line. the `./configure` should be preceded by `$ autoreconf -fi`.

**Comment by mikebrady** [comment]
Fixed now. Apologies!

**Comment by Joeknx** [comment]
Ah, great thank you!
