### ISSUE TITLE
Unable to listen on port 319

### ISSUE THREAD

**Issue by Joeknx** [mikebrady/nqptp#25]
Sorry, I'v been running in another problem.

Everything was running before the update. 
I checked that there is no nqptp service running under /lib/systemd/system

Now I get:

root@shairport-sync:~# nqptp -v
         0.000739953 "nqptp.c:168" Version: 1.2.4, smi10. Clock ID: "d83addfffe4340e6".
         0.001290425 "nqptp-utilities.c:109" *fatal error: unable to listen on port 319. The error is: "Address already in use". NQPTP must run as root to access this port. Or is another PTP daemon -- possibly another instance on NQPTP -- running already?
         0.000236928 "nqptp.c:114" goodbye

**Comment by mikebrady** [comment]
Thanks. So, you must make sure that the service file is removed:
```
# rm /lib/systemd/system/nqptp.service
# systemctl daemon-reload
```
(Note, you must be in supervisor mode to do anything with a `#` prompt.))

Then you do a:
```
# make install
```
of the NQPTP you've just built (i.e. 1.2.4).

Then you must do a restart of NQPTP:
```
# systemctl restart nqptp
```
Then you can check if `nqptp` is running as a daemon:
```
$ ps aux | grep nqptp
```
This is what I get:
```
$ ps aux | grep nqptp
nqptp      54654  2.0  0.1   2432  1524 ?        SLs  Sep17  29:21 /usr/local/bin/nqptp
pi         65676  0.0  0.0   6044   748 pts/4    S+   19:47   0:00 grep --color=auto nqptp
```
The second line is just me (`pi`) grepping it. If you're getting this, you're good -- you don't need to try to run it from the command line, and you shouldn't have permission to anyway.

**Comment by Joeknx** [comment]
Thanks for the detailed instructions!

`/lib/systemd/system/nqptp.service`

I tried to remove it, but it wasn't there.

I also tried to remove
`/usr/local/bin/nqptp`

the daemon seems to be running:
`root@shairport-sync:~# ps aux | grep nqptp
root      1332  0.3  0.3   2348  1460 ?        SLs  Sep18   2:03 /usr/local/bin/nqptp
root      6215  0.0  0.1   7452   516 pts/0    S+   07:53   0:00 grep nqptp
`

after several attempts of 
`make install`

I still get:
`nqptp -v`

` *fatal error: unable to listen on port 319. The error is: "Address already in use". NQPTP must run as root to access this port. Or is another PTP daemon -- possibly another instance on NQPTP -- running already?
         0.000228855 "nqptp.c:114" goodbye
`

**Comment by mikebrady** [comment]
Thanks again. This is puzzling. So, let's take it in stages.

1. What version of NQPTP is installed? To find out, please enter:
   ```
   $ nqptp -V
   ```
   and post the results here.
2. Where is the NQPTP app located? To find out, please enter:
   ```
   $ which -a nqptp
   ```
   and post the results here.
3. Finally, for now, let's see if there is another copy of the `nqptp.service` file anywhere. There shouldn't be, but let's see.
   ```
   $ find  / -name "nqptp.service" 2>/dev/null
   ```
   and post the results here.

Thanks!

For reference, I get the following:
```
$ nqptp -V
Version: 1.2.4. Shared Memory Interface Version: smi10.

$ which -a nqptp
/usr/local/bin/nqptp

$ find  / -name "nqptp.service" 2>/dev/null
/home/pi/nqptp/nqptp.service
/sys/fs/cgroup/system.slice/nqptp.service
/usr/local/lib/systemd/system/nqptp.service
/etc/systemd/system/multi-user.target.wants/nqptp.service

```

**Comment by mikebrady** [comment]
Okay I found it, and again, my apologies. The files to remove now include `/usr/local/lib/systemd/system/nqptp.service`, as well as `/lib/systemd/system/nqptp.service`. I've updated the README.

**Comment by mikebrady** [comment]
Thanks for your persistence, and your patience!

Is that a response to `$ nqptp -v`?

If so, could you post the response to
```
$ ps aux | grep nqptp
```
please?

Also `$ nqptp -V` (capital V).

**Comment by Joeknx** [comment]
Yes it's a response to nqptp -v

If I type:
`systemctl restart nqptp`

First time 
`nqptp -v`

`0.000762602 "nqptp.c:168" Version: 1.2.4-2-g2d4f870, smi10. Clock ID: "d83addfffe4340e6".
         0.000396977 "nqptp.c:201" *fatal error: cannot open shared memory "/nqptp".
         0.000091563 "nqptp.c:114" goodbye`

Second time
`nqptp -v`

`0.000726455 "nqptp.c:168" Version: 1.2.4-2-g2d4f870, smi10. Clock ID: "d83addfffe4340e6".
         0.001303693 "nqptp-utilities.c:109" *fatal error: unable to listen on port 319. The error is: "Address already in use". NQPTP must run as root to access this port. Or is another PTP daemon -- possibly another instance on NQPTP -- running already?
         0.000232395 "nqptp.c:114" goodbye
`

`$ ps aux | grep nqptp`
gives me:

`nqptp     1076  0.3  0.3   2348  1524 ?        SLs  16:21   0:00 /usr/local/bin/nqptp
johannes  1084  0.0  0.1   7452   496 pts/0    S+   16:23   0:00 grep --color=auto nqptp`

`$ nqptp -V`
gives me:

`Version: 1.2.4-2-g2d4f870. Shared Memory Interface Version: smi10.`

**Comment by mikebrady** [comment]
Super, thanks. Well, all that means that NQPTP is installed and running, as intended, as a "daemon" in the background.
To explain the error messages, when you run the command `$ nqptp -v` from the command line, it starts a second copy of NQPTP. This finds that it can't continue, either because the first copy of NTPTP -- the daemon -- is already running (it would have started at system startup) and already has ports 319 and 320 or has already created the shared memory interface at `/nqptp`. Either way, the second copy should issue an error message and terminate.

Just to check, if you reboot the pi and then run:
```
$ ps aux | grep nqptp
```
You should get something like you show above:
```
nqptp     1076  0.3  0.3   2348  1524 ?        SLs  16:21   0:00 /usr/local/bin/nqptp
johannes  1084  0.0  0.1   7452   496 pts/0    S+   16:23   0:00 grep --color=auto nqptp
```
(I am puzzled by the two different responses to `$ nqptp -v` though. I don't get that.)

Anyway, it really does look as if the new version of NQPTP is installed and running, so, if you've updated Shairport Sync, it should be running as a daemon in the background. You can check that both it and NQPTP are running as follows:

```
ps aux | grep -e nqptp -e shair
```
should return something like this:
```
$ps aux | grep -e nqptp -e shair
nqptp      79030  1.6  0.1   2432  1584 ?        SLs  11:22   4:20 /usr/local/bin/nqptp
shairpo+   86634  8.4  2.2 1176124 21276 ?       Ssl  15:35   0:17 /usr/local/bin/shairport-sync --log-to-syslog
pi         86690  0.0  0.0   5912   672 pts/2    S+   15:39   0:00 grep --color=auto -e nqptp -e shair
```
If you're not getting that, could you do:
```
$ shairport-sync -V
```
and post it here, please?
