### ISSUE TITLE
Possible missing $(DESTDIR) in Makefile.am

### ISSUE THREAD

**Issue by oliverbr** [mikebrady/nqptp#27]
Sorry if this is a stupid question, I'm not really comfortable with Make/Automake (and, honestly, the entire stack) yet.

I'm currently trying to update some dependencies in [duhow/xiaoai-patch](https://github.com/duhow/xiaoai-patch) and, because of that, came across the following line in [Makefile.am](https://github.com/mikebrady/nqptp/blob/10969eaa0ba71287efd46252910701809b50fb36/Makefile.am#L23):

```bash
install-exec-hook:
if BUILD_FOR_LINUX
# NQPTP runs as user/group nqptp/nqptp on Linux and uses setcap to access ports 319 and 320
	setcap 'cap_net_bind_service=+ep' $(bindir)/nqptp
```

In #7, the DESTDIR variable was added, and I believe that variable is also necessary for the call to `setcap`. If left unedited, running Make will try to modify `/usr/bin/nqptp` instead of the one in the folder set by DESTDIR.

This is how I was able to fix my build:

```bash
install-exec-hook:
if BUILD_FOR_LINUX
# NQPTP runs as user/group nqptp/nqptp on Linux and uses setcap to access ports 319 and 320
	setcap 'cap_net_bind_service=+ep' $(DESTDIR)$(bindir)/nqptp
```

Is this correct? I can also submit a PR, but I thought I'd ask first.

**Comment by mikebrady** [comment]
Thanks for the post. I guess you’re right, but the `Makefile.am` in the `development` branch has changed and doesn’t use `setcap` anymore — it’s worth taking a look, I believe.

**Comment by oliverbr** [comment]
Ah, true, I should have looked there, too. The project I mentioned cross-compiles to a non-systemd target, though, so the `development` branch effectively reverts `setcap` change. I think that will do for this issue - thanks for replying!
