### ISSUE TITLE
unable to listen on IPv4 port 319

### ISSUE THREAD

**Issue by bruturb** [mikebrady/nqptp#8]
`nqptp -v` returns following error:
```
0.000030945 "nqptp.c:158" startup
0.001729555 "nqptp-utilities.c:92" *fatal error: unable to listen on IPv4 port 319. The error is: "Address already in use". Daemon must run as root. Or is a separate PTP daemon running?
0.000077685 "nqptp.c:107" goodbye
```

It runs as root and is the only process listening to 319. I'm not aware of any other PTP daemon on my system. Any idea how can I fix it?

**Comment by mikebrady** [comment]
Thanks for the post. There are some Unix commands, e.g. `lsof` (?) to investigate what ports are open and what processes are associated with them. Could two copies of `nqptp` be running?

**Comment by bruturb** [comment]
```
udp        0      0 0.0.0.0:319             0.0.0.0:*                           851/nqptp           
udp6       0      0 :::319                  :::*                                851/nqptp       
```

**Comment by mikebrady** [comment]
Apologies for the delay. It looks as if `nqptp` is running and listening to port 319, as it should. If you executed the command above as `root` at this point, you would get the same fatal error message because another copy of `nqptp` is already running.

**Comment by bruturb** [comment]
No worries, Mike. I appreciate your work for the community.
I'm confused. I ran both commands as `root`. I removed `nqptp` and checked for old copies. Nothing left. New installation as `root` and still the same symptoms.
This seems to block my `shairport-sync` installation (connection attempts take very long and fail every time). I don't know what I'm doing wrong.

**Comment by mikebrady** [comment]
Thanks, and apologies if this is all a bit obvious -- I'm puzzled too 🤔.
If you do the following:
```
$ ps aux | grep nqptp
```
...could you post the response please?

**Comment by bruturb** [comment]
Voilà!
```
root       691  0.6  0.0   2212   484 ?        SLs  Sep13   9:19 /usr/local/bin/nqptp
root      7307  0.0  0.0   4560   588 pts/0    S+   09:13   0:00 grep nqptp
```

**Comment by mikebrady** [comment]
Thanks. So that means `nqptp` is running as a system service. Now, if you want to troubleshoot `nqptp`, the easiest way to do it is to stop it running as a service and run it instead from the command line. To stop the service, do:
```
$ sudo systemctl stop nqptp
```
Then, to run it from the command line with one level of log verbosity, do:
```
$ sudo nqptp -v
```
Could you let us know how this works out for you by posting the start of the log please?

**Comment by bruturb** [comment]
`         0.000032296 "nqptp.c:158" startup`

**Comment by mikebrady** [comment]
Okay, good. Now, keep it running and do the same thing with Shairport Sync. That is, stop the Shairport Sync service and run it instead from the command line:
```
$ sudo systemctl stop shairport-sync
```
and then:
```
$ shairport-sync -vu
```
(No need to run Shairport Sync from `root` mode.)

You should get some responses from the `nqptp` log and from the `shairport-sync` log.
Could you let us see some of them please?

**Comment by bruturb** [comment]
Short: It's working amazing now!
Long: I had to work on some other projects on my Raspberry Pi and I upgraded it to Bullseye. It came with a whole bunch of updates. Quick reboot and... magic! No problems whatsoever. So what was the issue in the first place? Hard to say. Anyway, thank you very much, Mike!

**Comment by mikebrady** [comment]
Excellent!
