### ISSUE TITLE
Limitation of MAX_CLOCKS 32 required?

### ISSUE THREAD

**Issue by nkvoll** [mikebrady/nqptp#9]
When adding more than 16 Airplay 2 speakers to a group (around 14 of which were `shairport-sync`), the `nqptp` services started dying with the log message `fatal error: Clock tables full!`.

Just grepping a little through the code, it looks like it's caused by `#define MAX_CLOCKS 32`, which at face value would look like it should set a maximum number of devices to 32?

I'm not sure of the real-world consequences (and I haven't adjusted all output to match their audio backend latencies etc), but to get past this, I just did a quick `sed -i -e 's/define MAX_CLOCKS 32/define MAX_CLOCKS 256/g' nqptp-shm-structures.h` and rebuilt `nqptp`, and I had no more complaints from `nqptp` going to 21 devices. After removing a non-wired Airplay 2 speaker from the group, `shairport-sync` also stopped logging most complaints of large positive/negative syncs, lead times and too small packets.

This leaves me wondering whether it needs to be 32, could be user-configurable or just set as higher by default? It's not clear to me what the drawbacks are by doing what I did but it made me wonder :)

**Comment by mikebrady** [comment]
Thanks for the very interesting report. I’ll admit that `NQPTP` hasn’t been tested with more than six or seven devices. Certainly there is no reason not to set `MAX_CLOCKS` to a higher number — it will just take up some more memory. Off hand (not near a machine) the amount of memory allocated is quite small. It has varied a good deal over the course of development, but now it’s not huge. I’ll think about adding it a command line option. Making it dynamic is a bit of a headache TBH and may not be worthwhile.

However, I’m also interested in the problems that went away when the wired device was removed. Can you say what kind of device it was and would you have any logs showing the problems please?

**Comment by nkvoll** [comment]
> However, I’m also interested in the problems that went away when the wired device was removed. Can you say what kind of device it was and would you have any logs showing the problems please?

It was a **non**-wired device I removed (Ikea Symfonisk / Sonos bedside lamp) with far from perfect wireless connectivity. Unfortunately I do not have the logs anymore, but I will probably create a similar setup/config again in a few days and can report back with logs then. Due to how my setup is done atm, I cannot separate `nqptp` logs from `shairport-sync` logs however.. would that be a problem?

**Comment by th0u** [comment]
Would it be possible to make nqptp more resilient when reaching MAX_CLOCKS, instead of dying? 
In the current setup, the service can be shut down remotely, by feeding a long (32+) peer list to Port 9000/udp.

**Comment by mikebrady** [comment]
Thanks for the suggestion. Let me take a look at this. Is a peer list that is that long a common occurrence, or is it something you’ve just noticed?

**Comment by th0u** [comment]
No "real" runtime issue here. I was just fiddling around with the network part of the nqptp code sending some long bogus lists to 9000/udp and found that it then died.

**Comment by mikebrady** [comment]
Thanks for that. I’ll raise the limit and also stop it exiting when the limit is exceeded.

**Comment by mikebrady** [comment]
Hi there. I [think I] fixed this in the latest version. (You'll need to update Shairport Sync at the same time though -- the interface has changed slightly.)
